######################################################################
# Automatically generated by qmake (3.0) ?? ?? 28 00:53:03 2017
######################################################################

QT += widgets

TEMPLATE = app
TARGET = sample
INCLUDEPATH += .

# Input
HEADERS += sample.h
SOURCES += sample.cpp
