######################################################################
# Automatically generated by qmake (3.0) ?? ?? 28 15:07:24 2017
######################################################################

QT += widgets
TEMPLATE = app
TARGET = sortDialog
INCLUDEPATH += .

# Input
HEADERS += dialog.h
FORMS += dialog.ui
SOURCES += dialog.cpp main.cpp
